spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

guardian:
  security:
    require-https: ${REQUIRE_HTTPS:true}
  mail:
    enabled: ${APP_MAIL_ENABLED:false}

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
